---
output: html_document
editor_options: 
  chunk_output_type: console
---

# SFARI Phenotypic Data – Researcher Feedback Survey Results

Results shared at CDWG - focus on coding preferences

Setup

```{r setup, echo=FALSE, message = FALSE}

library(table1)
library(ggplot2)
library(tidyverse)

# load data as survey
source("scripts/setup.R")
survey <- setup()$data

# subset data
coding <- survey[survey$share_coding_preferences_check == "Yes",]

knitr::opts_chunk$set(
  fig.width = 10,
  fig.height = 6,
  fig.align = "center",
  dpi = 300
)
```


## Overall Experience

Sample
```{r Overall Experience Sample, echo=FALSE}

# prep labels for table1
label(survey$edu_clean) <- "Highest Degree of Education"
label(survey$current_role) <- "Current Role"

table1(
  x = ~ edu_clean + current_role + compiled_pheno_role_primary_hands_on,
  data = survey
)

role_items <- grep("pheno_roles_", names(survey), value = TRUE)
survey %>%
  select(all_of(role_items)) %>%
  pivot_longer(cols = everything(), names_to = "tool", values_to = "selected") %>%
  filter(selected == "yes") %>%
  count(tool) %>%
  ggplot(aes(x = reorder(tool, -n), y = n)) +
  geom_col(fill = "steelblue") +
  labs(x = "Role with data", y = "Count", title = "Number of Participants Selecting Each Role")

barplot(table(survey$n_pheno_datasets), main = "Prior to working with SFARI phenotypic data,\n how many other phenotypic datasets\n had you worked with?", ylab = "Count", xlab = "Number of datasets")

```

```{r Combining sfari pheno data, echo=FALSE}
barplot(table(survey$combined_sfari_pheno),
        main = "Have you ever combined phenotypic data \nacross multiple SFARI cohorts? \n(e.g., merged questionnaire data between SPARK and SSC)", ylab = "Count")

combine_pheno_table <-
  as.data.frame(xtabs(
    formula = ~ combined_sfari_pheno + combined_sfari_pheno_text,
    data = survey
  )) %>%
  pivot_wider(id_cols = combined_sfari_pheno_text,
              names_from = combined_sfari_pheno,
              values_from = Freq)  %>%
  rename("combination" = combined_sfari_pheno_text)





barplot(table(survey$combined_sfari_nonsfari),
        main = "Have you ever combined SFARI phenotypic data\n with data collected outside the Simons Foundation?\n (e.g., combined SPARK and NDAR data)", ylab = "Count")

combine_sfarinonsfari_table <-
  as.data.frame(
    xtabs(
      formula = ~ combined_sfari_nonsfari + combined_sfari_nonsfari_text,
      data = survey
    )
  ) %>%
  pivot_wider(id_cols = combined_sfari_nonsfari_text,
              names_from = combined_sfari_nonsfari,
              values_from = Freq)  %>%
  rename("combination" = combined_sfari_nonsfari_text)
```

Plot of Data Value Coding Challenges
```{r Data Value Challenges Plot, echo=FALSE}

# format data and values for barplot
value_chal_long <- survey %>%
  select(
    "datachal_coding_ambig",
    "datachal_coding_incon",
    "datachal_coding_incompat",
    "datachal_null_ambig"
  ) %>%
  pivot_longer(cols = everything(),
               names_to = "Question",
               values_to = "Response") %>%
  mutate(
    Question = recode(
      Question,
      "datachal_coding_ambig" = "Codes were ambiguous or undefined",
      "datachal_coding_incon" = "Codes were inconsistent within a dataset",
      "datachal_coding_incompat" = "Codes were incompatible with how I needed them for analyses",
      "datachal_null_ambig" = "Sources of missing data (null values) were ambiguous"
    )
  ) %>%
  # wrap strings for better formatting in plot
  mutate(Question = str_wrap(Question, width = 20)) %>%
  mutate(Response = str_wrap(Response, width = 40))
  
# Create grouped bar chart
value_chal_plot <-
  ggplot(value_chal_long, aes(x = Question, fill = Response)) +
  geom_bar(position = "dodge") +
  scale_fill_brewer(palette = "Dark2", na.value = "grey80") +
  labs(y = "Count of Responses", x = "Value Coding Issue") +
  theme_minimal(base_size = 12) +
  theme(plot.background = element_rect(
    color = "black",
    fill = NA,
    linewidth = 1.0
  ))


value_chal_plot_export <- value_chal_plot + theme(
    axis.text.x = element_text(color = "black", size = 16),
    axis.title.x = element_text(size = 18, face = "bold"),
    axis.title.y = element_text(size = 18, face = "bold"),  
    legend.key.height = unit(1.5, "cm"),
    # Increase space between legend items vertically, bold "this cause challenges for me"
    legend.text = element_text(
      color = "black"
    )
  )
  
# export for slides
ggsave("plots/value_chal_plot.png", width = 16, height = 8, plot = value_chal_plot_export, dpi = 1200, bg = "white")

value_chal_plot # display with settings set in setup

```

```{r value coding challenge elaborations}

## these comments were manually identified as being related to value coding
survey$challenge_other_describe[survey$timestamp %in% c("4/17/2025 17:08:47", "4/30/2025 15:37:08")]


```

## Coding Preferences

```{r describe sample}



#### describe sample ####

label(coding$edu_clean) <- "Highest Degree of Education"
label(coding$current_role) <- "Current Role"

label(coding$compiled_pheno_role_primary_hands_on) <- "Experience in primary hands-on role"

table1(
  x = ~ edu_clean + current_role + compiled_pheno_role_primary_hands_on, 
  data = coding
)


## software tools -- figure out a better way to display and summarize this 
tool_labels <- c(
  "proc_tool_excel_automate" = "Excel Adv",
  "proc_tool_excel_basic" = "Excel Basic",
  "proc_tool_sas" = "SAS",
  "proc_tool_stata" = "Stata",
  "proc_tool_r" = "R",
  "proc_tool_spss" = "SPSS",
  "proc_tool_python" = "Python",
  "proc_tool_jupyter" = "Jupyter Notebook"
)
proc_tools_items <- grep("proc_tool", names(coding), value = TRUE)
coding %>%
  select(all_of(proc_tools_items)) %>%
  pivot_longer(cols = everything(), names_to = "tool", values_to = "selected") %>%
  filter(selected == "yes") %>%
  count(tool) %>%
  ggplot(aes(x = reorder(tool, -n), y = n)) +
  geom_col(fill = "steelblue") +
  labs(x = "Processing Tool", y = "Count", title = "Number of Participants Selecting Each Processing Tool") +
  scale_x_discrete(labels = tool_labels) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

proc_tools_items <- grep("proc_tool", names(survey), value = TRUE)
survey %>%
  select(all_of(proc_tools_items)) %>%
  pivot_longer(cols = everything(), names_to = "tool", values_to = "selected") %>%
  filter(selected == "yes") %>%
  count(tool) %>%
  ggplot(aes(x = reorder(tool, -n), y = n)) +
  geom_col(fill = "steelblue") +
  labs(x = "Processing Tool", y = "Count", title = "Number of Participants Selecting Each Processing Tool") +
  scale_x_discrete(labels = tool_labels) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# count excel alone
sum(
  coding$proc_tool_excel_basic == "yes" &
    coding$proc_tool_excel_automate == "no" &
    coding$proc_tool_r == "no" &
    coding$proc_tool_python == "no" &
    coding$proc_tool_spss == "no" &
    coding$proc_tool_stata == "no" &
    coding$proc_tool_sas == "no"
)

# count basic excel + SPSS only
sum(
  coding$proc_tool_excel_basic == "yes" &
    coding$proc_tool_excel_automate == "no" &
    coding$proc_tool_r == "no" &
    coding$proc_tool_python == "no" &
    coding$proc_tool_spss == "yes" &
    coding$proc_tool_stata == "no" &
    coding$proc_tool_sas == "no"
)

# count basic excel + stata only 
sum(
  coding$proc_tool_excel_basic == "yes" &
    coding$proc_tool_excel_automate == "no" &
    coding$proc_tool_r == "no" &
    coding$proc_tool_python == "no" &
    coding$proc_tool_spss == "no" &
    coding$proc_tool_stata == "yes" &
    coding$proc_tool_sas == "no"
)

# count basic excel + programming 
sum(
  coding$proc_tool_excel_basic == "yes" &
    (coding$proc_tool_excel_automate == "yes" |
      coding$proc_tool_r == "yes" |
    coding$proc_tool_python == "yes" | coding$proc_tool_sas == "yes")
)

# % programming - coding sample
sum(
    (coding$proc_tool_excel_automate == "yes" |
      coding$proc_tool_r == "yes" |
    coding$proc_tool_python == "yes" | coding$proc_tool_sas == "yes")
) / nrow(coding)

# % programming - larger sample
sum(
    (survey$proc_tool_excel_automate == "yes" |
      survey$proc_tool_r == "yes" |
    survey$proc_tool_python == "yes" | survey$proc_tool_sas == "yes"), na.rm = TRUE
) / nrow(survey)

# frequency of responses for processing_proficiency 
barplot(table(coding$n_pheno_datasets), main = "Frequency: Number of pheno datasets pre-SFARI")

# frequency of responses for processing_proficiency 
barplot(table(coding$processing_proficiency), main = "Frequency: How proficient are you (1-5)")
```

```{r coding subset}

coding_red <- coding[grep("^coding|role|processing_proficiency|^proc_tool", names(coding))]

```

```{r coding boolean results}

barplot(table(coding$coding_boolean), main = "Preference for boolean value codes")

# pro string explanations
coding$coding_boolean_describe[coding$coding_boolean %in% c("4", "5") & !is.na(coding$coding_boolean_describe)]

# pro-int explanations
coding$coding_boolean_describe[coding$coding_boolean %in% c("1", "2") & !is.na(coding$coding_boolean_describe)]

# neutral explanations
coding$coding_boolean_describe[coding$coding_boolean == "3" & !is.na(coding$coding_boolean_describe)]
```

```{r coding nominal results}

barplot(table(coding$coding_nominal), main = "Preference for nomical categorical")

# pro string explanations
coding$coding_nominal_describe[coding$coding_nominal %in% c("4", "5") & !is.na(coding$coding_nominal_describe)]

# pro-int explanations
coding$coding_nominal_describe[coding$coding_nominal %in% c("1", "2") & !is.na(coding$coding_nominal_describe)]

# neutral explanations
coding$coding_nominal_describe[coding$coding_nominal == "3" & !is.na(coding$coding_nominal_describe)]

```

```{r coding ordinal results}

barplot(table(coding$coding_ordinal), main = "Preference for ordinal categorical")

# pro string explanations
coding$coding_ordinal_describe[coding$coding_ordinal %in% c("4", "5") & !is.na(coding$coding_ordinal_describe)]

# pro-int explanations
coding$coding_ordinal_describe[coding$coding_ordinal %in% c("1", "2") & !is.na(coding$coding_ordinal_describe)]

# neutral
coding$coding_ordinal_describe[coding$coding_ordinal == "3" & !is.na(coding$coding_ordinal_describe)]

```

```{r coding special response results}

barplot(table(coding$coding_dk_pna), main = "Preference for special cases")

# pro string explanations
coding$coding_dk_pna_describe[coding$coding_dk_pna %in% c("4", "5") & !is.na(coding$coding_dk_pna_describe)]

# pro int explanations
coding$coding_dk_pna_describe[coding$coding_dk_pna %in% c("1", "2") & !is.na(coding$coding_dk_pna_describe)]

# neutral
coding$coding_dk_pna_describe[coding$coding_dk_pna == "3" & !is.na(coding$coding_dk_pna_describe)]

```

```{r coding skipped results}

barplot(table(coding$coding_skipped), main = "Preference for skipped")

# pro-code
coding$coding_skipped_describe[coding$coding_skipped %in% c("4", "5") & !is.na(coding$coding_skipped_describe)]

# pro-null
coding$coding_skipped_describe[coding$coding_skipped %in% c("1", "2") & !is.na(coding$coding_skipped_describe)]

# neutral
coding$coding_skipped_describe[coding$coding_skipped == "3" & !is.na(coding$coding_skipped_describe)]

```

```{r coding checklist results}

barplot(table(coding$coding_checklists), main = "Preference for checklists")

coding$coding_checklists_describe[coding$coding_checklists_describe == "checked = 1; unchecked = 0 or null depending on context" & !is.na(coding$coding_checklists_describe)]

coding$coding_checklists_describe[coding$coding_checklists_describe == "checked = 1; unchecked = 0" & !is.na(coding$coding_checklists_describe)]

coding$coding_checklists_describe[coding$coding_checklists_describe == "checked = 1; unchecked = null"  & !is.na(coding$coding_checklists_describe)]
```
