---
output: html_document
editor_options: 
  chunk_output_type: console
---

Code for Science Meeting Presentation on July 2, 2025
```{r setup, echo=FALSE, message = FALSE}

library(table1)
library(ggplot2)
library(tidyverse)
library(treemap)

# loads data as survey
source("scripts/setup.R")
output <- setup(responses_file = "data/responses_2025-05-11.csv")
survey <- output$data
metadata <- output$metadata[c("name", "Question")]
```

```{r plotting function}

# TO DO -- make it so ## Data Combining category colors match the others (since there is an extra response option)

create_plot <- function(df, plot_variables, x_title, metadata, plot_na = FALSE, response_to_sort = NULL, response_order = NULL, variable_order = NULL) {
  # response_to_sort is a string that indicates which response to order questions by on the x-axis. should not be used if variable_order is set
  # response_order is a vector of responses e.g., c("This caused challenges for me", ....)
  # metadata is DF with name and Question columns used to map variable name to "Question" for plotting
  # DOESNT EXIST: variable_order is a vector that indicates what order variables should appear on the x-axis. should not be used if response_to_sort is set. will override response_to_sort
  
  level_questions_by_response <- function(data_long) {
    order <- data_long %>%
      group_by(Question, Response) %>%
      mutate(n = n()) %>%
      distinct() %>%
      filter(Response == response_to_sort) %>%
      arrange(desc(n)) %>%
      ungroup() %>%
      select(Question) %>%
      pull()
    
    # Apply order to levels
    data_long <- data_long %>%
      mutate(Question = factor(Question, levels = order))
    
    return(data_long)
  }
  
  # format data and values for barplot
  data_long <- df %>%
    select(all_of(plot_variables)) %>%
    pivot_longer(cols = everything(),
                 names_to = "name",
                 values_to = "Response") %>%
    left_join(metadata, by = "name") %>%
     
    # wrap strings for better formatting in plot
    mutate(Question = str_wrap(Question, width = 20),
           Response = str_wrap(Response, width = 35))
  

  # impacts whether missing responses are included in plot
  if (!plot_na) {
    data_long <- data_long %>%
      filter(!is.na(Response))
  }
  
  # impacts legend order
  if (!missing(response_order)) { 
    
    data_long <- data_long %>%
      ### apply str_wrap to match formatting applied to Response above
      mutate(Response = factor(Response, levels = str_wrap(response_order, width = 35)))
  }
  
  # impacts variable order on x-axis
  if (!missing(response_to_sort)) { 
    data_long <- level_questions_by_response(data_long) # function defined above
  }
  
  # impacts variable order on x-axis (will overwrite changes from response_to_sort)
  if (!missing(variable_order)) {

    # look up corresponding Question value based on variable names
    ### apply str_wrap to match formatting applied to Response above
    lookup_vector <- setNames(str_wrap(metadata$Question, width = 20), metadata$name)
    mapped_vector <- lookup_vector[variable_order]
    
    # set order
    data_long <- data_long %>%
      mutate(Question = factor(Question, levels = mapped_vector))
  }
  
  # create summary data for plotting
  data_summary <- data_long %>%
    
    # summarize
    group_by(Question, Response) %>%
    summarise(n = n(), .groups = "drop") %>%
    # Make sure all combinations exist -- this will ensure "bars" with 0 counts still added to graph
    complete(Question, Response, fill = list(n = 0)) %>%
    # calculate percents to add to plot
    group_by(Question) %>%
    mutate(pct = n / sum(n) * 100)

  
  totals <- data_summary %>%
    group_by(Question) %>%
    summarise(total_n = sum(n))

    # note: the final color will be at the bottom
   if (length(unique(data_summary$Response)) == 5) {
            ### update this color scheme 
           color_vector = c("pink", "blue", "#7570b3", "#1b9e77", "#d95f02")
   } else if (length(unique(data_summary$Response)) == 4) {
           color_vector = c("darkslategrey", "#1b9e77", "#7570b3", "#d95f02")
   } else if (length(unique(data_summary$Response)) == 3) {
           color_vector = c("#1b9e77", "#7570b3", "#d95f02")
   } else if (length(unique(data_summary$Response)) == 2) {
           color_vector = c("#1b9e77", "#d95f02")
   }

  # Create stacked bar chart -- plot %, print total N on top
  plot <-
    ggplot(data_summary, aes(x = Question, y = n, fill = Response)) +
    geom_bar(stat = "identity", position = "fill") +  # stacked proportion bars
    # Add total N at top of each bar
    geom_text(
      data = totals,
      aes(x = Question, y = 1.05, label = paste0("n = ", total_n)),
      inherit.aes = FALSE,
      size = 5
    ) +
    scale_fill_manual(values = color_vector) +
    labs(y = "Proportion of Responses", x = x_title) +
    theme_bw() +
    theme(
      plot.background = element_rect(
        color = "black",
        fill = NA,
        linewidth = 1.0
      ),
      text = element_text(color = "black", size = 18),
      axis.text = element_text(color = "black", size = 14),
      legend.title = element_text(color = "black", size = 18),
      legend.text = element_text(color = "black", size = 14),
    )
  
  return(plot)
}


ggsave2 <- function(figure_path) {
  ggsave(figure_path, width = 17, height = 8, bg = "white", dpi = 300)
}


```

# Sample

```{r education, degree, current role}

# table: highest degree ----

# prep labels
label(survey$edu_clean) <- "Highest Degree of Education"

table1(
  x = ~ edu_clean,
  data = survey
)

# bar plot: degree field ----
degree_field_plot <- survey %>%
  count(degree_field_cleaned) %>% # count occurrences
  ggplot(aes(x = reorder(degree_field_cleaned,-n), y = n)) + # reorder factor by count descending
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Degree Field",
       y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 55, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12))

degree_field_plot
ggsave2("figs/sample_field.png")



# tree map of current role ----
role_tree_map <- survey %>%
  mutate(
    # assign role_group
    role_group = case_when(
      grepl("Professor", current_role) ~ "Professor",
      grepl("Simons|Research Assistant", current_role) ~ "Research Adjacent",
      grepl("student|trainee|Student|Postdoctoral|fellow", current_role) ~ "Student/Fellow",
      grepl("Industry|Government|Scientist|Clinician-Researcher", current_role ) ~ "Non-professor researcher",
      TRUE ~ NA_character_
    ), 
    
    # clean up current_role
    current_role = case_when(
      grepl("Clinician-Researcher", current_role) ~ "Clinician-Researcher",
      grepl("Research Assistant", current_role) ~ "Research Assistant (staff)",
      grepl("Doctoral Student", current_role) ~ "Doctoral Student",
      TRUE ~ current_role
    )
  )  %>%
  select(role_group, current_role) %>%
  group_by(role_group, current_role) %>%
  summarise(n = n(), .groups = "drop") %>%
  treemap(
    .,
    index = c("role_group", "current_role"),
    vSize = "n",
    type = "index",
    fontsize.labels=c(0,50))

role_tree_map

```

```{r pheno dataset experience}

# bar plot: which SFARI datasets ----
sfari_datasets_count <- survey %>%
  select(starts_with("worked_with")) %>%
  mutate(n_worked_with = rowSums(select(., starts_with("worked_with")) == "yes")) 

barplot(table(sfari_datasets_count$n_worked_with), main = "Number of SFARI pheno studies* worked with", ylab = "Count", xlab = "Number of datasets")

sfari_datasets_plot <- survey %>%
  select(starts_with("worked_with")) %>%
  pivot_longer(cols = everything(), names_to = "study", values_to = "selected") %>%
  filter(selected == "yes") %>%
  count(study) %>%
  mutate(study = fct_reorder(study, n, .desc = TRUE),
         pct = n/nrow(survey) * 100) %>%
  ggplot(., aes(x = study, y = n)) +
    geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Study (select all that apply)", y = "Count") +
  theme_minimal() + 
  scale_x_discrete(labels = c(
    "worked_with_aic" = "AIC",
    "worked_with_rm" = "Research Match",
    "worked_with_searchlight" = "Searchlight",
    "worked_with_spark" = "SPARK",
    "worked_with_ssc" = "SSC"
  )) + 
  geom_text(aes(label = paste0(round(pct, 1), "%")),
              position = position_dodge(width = 0.9),
              vjust = -0.3, size = 7) +
  theme(
    text = element_text(color = "black", size = 20),
    axis.text.x = element_text(size = 18, colour = "black"),
    axis.text.y = element_text(size = 18, colour = "black")
  )

sfari_datasets_plot
ggsave2("figs/sample_datasets.png")

# roles with SFARI pheno datasets ----
## TO DO: add pct 
role_items <- grep("pheno_roles_", names(survey), value = TRUE)

barplot_data_roles <- survey %>%
  select(all_of(role_items)) %>%
  pivot_longer(cols = everything(), names_to = "role", values_to = "selected") %>%
  filter(selected == "yes") %>%
  count(role) %>%
  mutate(role = fct_reorder(role, n, .desc = TRUE),
         pct = n/nrow(survey) * 100) %>%
  ggplot(., aes(x = role, y = n)) +
    geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Role (select all that apply)", y = "Count",) +
  theme_minimal() + 
  scale_x_discrete(
    labels = c(
      "pheno_roles_pi" = "PI",
      "pheno_roles_coi" = "Co-I",
      "pheno_roles_determine_data" = "Determined which datasets \nor variables were relevant \nfor analyses",
      "pheno_roles_process" = "Managed or processed \ndata (primary person)",
      "pheno_roles_analyses" = "Conducted analyses \n(primary person)",
      "pheno_roles_ra" = "RA (assisted with data \nprocessing or analyses)"
    )) +
  geom_text(aes(label = paste0(round(pct, 1), "%")),
              position = position_dodge(width = 0.9),
              vjust = -0.3, size = 7) +
  theme(
    text = element_text(color = "black", size = 20),
    axis.text.x = element_text(angle = 40, hjust = 1, size = 18, colour = "black"),
    axis.text.y = element_text(size = 18, colour = "black")
  )

barplot_data_roles
#ggsave2("figs/sample_data_roles.png")
ggsave("figs/sample_data_roles.png", width = 17, height = 8, bg = "white", dpi = 300)

# number of pheno datasets ----

## TO DO: remake with GGPLOT, fix axis labels 
barplot(table(survey$n_pheno_datasets), main = "Prior to working with SFARI phenotypic data,\n how many other phenotypic datasets\n had you worked with?", ylab = "Count", xlab = "Number of datasets")
ggsave2("figs/sample_n_datasets.png")

```

```{r combining datasets}
combining_data_vars <- c("combined_sfari_pheno", "combined_sfari_pheno_nonpheno", "combined_sfari_nonsfari")

metadata_formatted <- metadata %>%
  mutate(
    Question = case_when(
      name == "combined_sfari_pheno" ~ "SFARI pheno + \nSFARI pheno",
      name == "combined_sfari_pheno_nonpheno" ~ "SFARI pheno + \nSFARI non-pheno",
      name == "combined_sfari_nonsfari" ~ "SFARI pheno + \nnon-SFARI pheno",
      TRUE ~ Question
    )
  )

create_plot(
  survey,
  plot_variables = combining_data_vars,
  metadata = metadata,
  x_title = "Combination", 
  response_order = c("Yes", "No, but I would like to", "No, and I don't plan to", "I tried to and it didn't work"), 
  variable_order = combining_data_vars

)

```

# Barriers and Challenges

```{r create challenge plots}

## Documentation and Metadata
meta_vars <- grep("^metachal", names(survey), value = TRUE)
create_plot(
  survey,
  meta_vars,
  "Documentation and Metadata Challenge",
  metadata = metadata,
  response_to_sort = "This caused challenges for me",
  response_order = c(
    "I did not notice this issue/this wasn't an issue with the dataset",
    "I noticed this but it wasn't an issue for me",
    "This caused challenges for me"
  )
)
ggsave2("figs/challenge_metadata.png")

## Data label and values
data_vars <- grep("^datachal", names(survey), value = TRUE)
create_plot(
  df = survey,
  plot_variables = data_vars,
  x_title = "Data Label and Value Challenge",
  metadata = metadata,
  response_to_sort = "This caused challenges for me",
  response_order = c(
    "I did not notice this issue/this wasn't an issue with the dataset",
    "I noticed this but it didn't cause a challenge for me",
    "This caused challenges for me"
  )
)
ggsave2("figs/challenge_label_value.png")

## Data Combining 
combine_vars <- grep("^combinechal", names(survey), value = TRUE)
create_plot(
  survey,
  combine_vars,
  "Data Combining Challenge",
  metadata = metadata,
  response_to_sort = "This caused challenges for me",
  response_order = c(
    "NA - have not merged/combined datasets",
    "I did not notice this issue/this wasn't an issue with the dataset",
    "I noticed this but it wasn't an issue for me",
    "This caused challenges for me"
  )
)
ggsave2("figs/challenge_combine.png")

## Data Processing and Analysis Challenges
procchal_vars <- grep("^procchal", names(survey), value = TRUE)
create_plot(
  survey,
  procchal_vars,
  "Data Processing and Analysis Challenge",
  metadata = metadata,
  response_to_sort = "This caused challenges for me",
  response_order = c(
    "I did not notice this issue/this wasn't an issue with the dataset",
    "I noticed this but it wasn't an issue for me",
    "This caused challenges for me")
)
ggsave2("figs/challenge_proc_analysis.png")
```

```{r barrier plots}
barrier_vars <- c("barrier_modifying_var", "barrier_combining_data", "barrier_interpreting")
create_plot(survey,
            barrier_vars,
            "Barrier",
            metadata = metadata,
            response_to_sort = "This was a barrier I faced",
            response_order = c("This was not a barrier I faced", "This was a barrier I faced")
)
ggsave2("figs/barrier.png")
```

```{r free text}

challenge_text <- as.data.frame(survey$challenge_other_describe[!is.na(survey$challenge_other_describe)])

barrier_text <- as.data.frame(survey$barrier_other_describe[!is.na(survey$barrier_other_describe)])

best_repo_text <- as.data.frame(survey$best_repo_describe[!is.na(survey$best_repo_describe)])

validity_text <- as.data.frame(survey$flags_describe[!is.na(survey$flags_describe)])

```

# Supplemental Features
```{r plots}
supp_vars <- c("supp_welcomepacket", "supp_releasenotes", "supp_dd", "supp_flags")
create_plot(
  survey,
  supp_vars,
  "Supplemental Features",
  metadata = metadata,
  #  response_to_sort = "Very helpful",
  response_order = c(
    "I didn't know this existed",
    "I knew this existed but didn't use it",
    "Unhelpful",
    "Somewhat helpful",
    "Very helpful"
  ),
  variable_order = c(
    "supp_dd",
    "supp_releasenotes",
    "supp_welcomepacket",
    "supp_flags"
  )
) + scale_fill_manual(values = c("pink", "blue", "#d95f02", "aquamarine3", "#1b9e77")) # change color scheme

ggsave2("figs/existing_supp.png")

useful_vars <- c("useful_code", "useful_softwaretips", "useful_analytic_guidance", "useful_integration_tools", "useful_data_mapping", "useful_data_explore_viz", "useful_standardized_varname", "useful_standardized_coding")

survey_recode <- survey %>%
  mutate(across(all_of(useful_vars), ~ case_when(
    .x == "Not applicable to my research" ~ "Not applicable or useful",
    .x == "Not useful" ~ "Not applicable or useful",
    .x == "Somewhat useful" ~ "Somewhat or very useful",
    .x == "Very useful" ~ "Somewhat or very useful",
    TRUE    ~ as.character(.x)  # keep other values as-is
  )))

# make Question more legible for plotting
metadata_rev <- metadata %>%
  mutate(Question = case_when(
    name == "useful_code" ~ "Example code",
    name == "useful_softwaretips" ~ "Software tips",
    name == "useful_analytic_guidance" ~ "Analytic guidance",
    name == "useful_integration_tools" ~ "Tools for data integration",
    name == "useful_data_mapping" ~ "Data mapping guidelines",
    name == "useful_standardized_varname" ~ "Standardized variable names",
    name == "useful_standardized_coding" ~ "Standardized value codes",    
    TRUE ~ Question  # keep other values as-is
    ))

create_plot(
  survey_recode,
  useful_vars,
  "Potential feature",
  metadata = metadata_rev,
  response_to_sort = "Somewhat or very useful",
  response_order = c("Somewhat or very useful", "Not applicable or useful")
)
ggsave2("figs/potential_supp_2cat.png")

create_plot(
  survey,
  useful_vars,
  "Potential feature",
  metadata = metadata_rev,
  response_to_sort = "Very useful",
  response_order = c(
    "Not applicable to my research",
    "Not useful",
    "Somewhat useful",
    "Very useful"
  )
) + scale_fill_manual(values = c("darkslategrey", "#d95f02", "aquamarine3", "#1b9e77")) # change color scheme

ggsave2("figs/potential_supp_4cat.png")

```

# Deeper investigation
```{r }
# of those that didnt know about the welcome packet - what studies have they worked with?

no_welc <- survey[survey$supp_welcomepacket == "I didn't know this existed" & !is.na(survey$supp_welcomepacket), grep("^worked_with", names(survey))]

helpful_welc <- survey[survey$supp_welcomepacket == "Very helpful" & !is.na(survey$supp_welcomepacket), grep("^worked_with", names(survey))]

```